### ISSUE TITLE
Installation doc

### ISSUE THREAD

**Issue by Eliott-B** [Smaug6739/Alexandrie#8]
Can we have an installation documentation ?  
[Here](https://github.com/Smaug6739/Alexandrie/wiki) you can add all your documentation for your application.  

The application is interesting but I want to store confidential data, so I want to deploy this application in local.  
The creation of a documentation is also positive for the maintenance of your application.

**Comment by Smaug6739** [comment]
Hello, you can use the [CONTRIBUTING.md](https://github.com/Smaug6739/Alexandrie/blob/main/CONTRIBUTING.md) file and the [database template file](https://github.com/Smaug6739/Alexandrie/blob/main/backend/database/alexandrie.sql) to setup the project. If you have bugs or questions tell me.

**Comment by eliott-b** [comment]
Thank you. I'm going to try
